## Exercise 1

In [8]:
#Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

import numpy as np

arr = np.arange(1, 11)
print(arr)
print()

reshaped_arr = arr.reshape(2, 5)

print(reshaped_arr)


[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Exercise 2

In [18]:
#Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

arr = np.arange(1, 21)
print(arr)

extracted_elements = arr[5:15]
print(extracted_elements)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15]


## Exercise 3

In [22]:
##Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

import pandas as pd

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
print(fruit_series)
print()
fruit_series['pears'] = 4

print(fruit_series)


apples     3
bananas    2
oranges    1
dtype: int64

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


## Exercise 4

In [28]:
## Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'age': [25, 30, 22, 35, 28, 40, 27, 33, 29, 31],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male']
}

df = pd.DataFrame(data)

print(df)


      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   35    Male
4     Emma   28  Female
5    Frank   40    Male
6    Grace   27  Female
7    Henry   33    Male
8      Ivy   29  Female
9     Jack   31    Male


## Exercise 5

In [30]:
## Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


df = pd.DataFrame(data)


occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

df['occupation'] = occupations


print(df)

      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male  Programmer
4     Emma   28  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   27  Female  Programmer
7    Henry   33    Male     Manager
8      Ivy   29  Female     Analyst
9     Jack   31    Male  Programmer


## Exercise 6

In [37]:
## Select the rows of the dataframe where the age is greater than or equal to 30.

filtered_df = df[df['age'] >= 30]

print(filtered_df)

    name  age gender  occupation
1    Bob   30   Male     Manager
3  David   35   Male  Programmer
5  Frank   40   Male     Analyst
7  Henry   33   Male     Manager
9   Jack   31   Male  Programmer


## Exercise 7

In [49]:
## Convert this dataframe to a csv file and read that csv file, finally display the contents.

csv_filename = "dataframe.csv"
df.to_csv(csv_filename, index=False)

df_read = pd.read_csv(csv_filename)
print(df_read)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male  Programmer
4     Emma   28  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   27  Female  Programmer
7    Henry   33    Male     Manager
8      Ivy   29  Female     Analyst
9     Jack   31    Male  Programmer
